create table if not exists public.duties (
  id bigint generated by default as identity primary key,
  duty_date date not null,
  room_number text not null,
  created_at timestamptz not null default now(),
  unique (duty_date, room_number)
);

alter table public.duties enable row level security;

drop policy if exists "Anyone can view duties" on public.duties;
create policy "Anyone can view duties" on public.duties
for select to anon, authenticated using (true);

drop policy if exists "Authenticated users can add duties" on public.duties;
create policy "Authenticated users can add duties" on public.duties
for insert to authenticated with check (true);

drop policy if exists "Authenticated users can edit duties" on public.duties;
create policy "Authenticated users can edit duties" on public.duties
for update to authenticated using (true) with check (true);

drop policy if exists "Authenticated users can delete duties" on public.duties;
create policy "Authenticated users can delete duties" on public.duties
for delete to authenticated using (true);
